// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as path from 'path';
import * as dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

// Load .env from workspace root
dotenv.config({ path: path.resolve(__dirname, '../../../../../.env') });

export default defineConfig({
  schema: 'schema.prisma',
  migrations: {
    path: 'migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
